# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xQ-yFMcrDpkWMOPhR177D0yftmUw8Ml
"""

# pip install streamlit rapidfuzz

import streamlit as st
from fuzzywuzzy import process

# List of items
items = ["US", "UK", "Canada", "Germany", "France", "Japan", "Australia", "China", "India", "Brazil"]

# Function to find the closest match using fuzzy matching
def find_closest_match(query, items):
    matches = process.extract(query, items, limit=1)
    return matches[0] if matches and matches[0][1] >= 80 else ("No match", 0)

# Streamlit app
def main():
    st.title("Closest Match Finder")

    # User input
    user_input = st.text_input("Type a country:", "").strip()

    # Find the closest match
    closest_match, confidence = find_closest_match(user_input, items)

    # Display result
    st.write(f"Closest match: {closest_match}")
    st.write(f"Confidence: {confidence}%")

if __name__ == "__main__":
    main()

