# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xQ-yFMcrDpkWMOPhR177D0yftmUw8Ml
"""


import streamlit as st
from fuzzywuzzy import process


initial_items = ["US", "UK", "Canada", "Germany", "France", "Japan", "Australia", "China", "India", "Brazil"]


def find_closest_match(query, items):
    query = query.lower()
    items_lower = [item.lower() for item in items]
    matches = process.extract(query, items_lower, limit=1)
    return matches[0] if matches and matches[0][1] >= 75 else ("No match", 0)





def main():
    st.title("Closest Match Finder")

    user_input = st.text_input("Type a country:", "").strip()

    st.sidebar.header("Manage Items")
    new_item = st.sidebar.text_input("Add a new item:")
    if st.sidebar.button("Add Item") and new_item:
        initial_items.append(new_item)

    st.sidebar.subheader("Current Items")
    st.sidebar.write(initial_items)

    closest_match, confidence = find_closest_match(user_input, initial_items)

    st.write(f"Closest match: {closest_match}")
    st.write(f"Confidence: {confidence}%")

if __name__ == "__main__":
    main()



